image: ruby:3.1.0-alpine

stages:
  - build
#  - test
#  - staging
#  - production

build:
  stage: build
  script:
    - gem install bundler -v 2.3.3 --no-document
    - bundle install --jobs $(nproc) "${FLAGS[@]}"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    when: always
    expire_in: 2h30min
    paths:
      - ./
