image: ruby:3.1.0-alpine

stages:
  - build
#  - test
#  - staging
#  - production

build:
  stage: build
  script:
    - gem install bundler -v 2.3.3 --no-document
    - bundle install --jobs $(nproc) "${FLAGS[@]}"
  # artifacts:
  #   name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
  #   when: always
  #   expire_in: 2h30min
  #   paths:
  #     - ./

staging:
  stage: staging
  variables:
    HEROKU_API_KEY: $HEROKU_STAGING_API_KEY
  script:
    - echo "deb http://toolbelt.heroku.com/ubuntu ./" > /etc/apt/sources.list.d/heroku.list
    - wget -O- https://toolbelt.heroku.com/apt/release.key | apt-key add -
    - apt-get update
    - apt-get install -y -qq nodejs build-essential heroku-toolbelt
    - gem install dpl
    - dpl --provider=heroku --app=staging-masonicmanagement --api-key=$HEROKU_STAGING_API_KEY
    - heroku run rake db:migrate db:seed --exit-code --app staging-masonicmanagement
  only:
    - develop
