image: ruby:3.1.0

stages:
  - build
  - image
#  - test
  - staging
#  - production

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  variables:
    BUILDER_IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker pull $BUILDER_IMAGE_TAG || echo "No pre-built image found."
    - docker build --cache-from $BUILDER_IMAGE_TAG -t $BUILDER_IMAGE_TAG -f Dockerfile . || docker build -t $BUILDER_IMAGE_TAG -f Dockerfile . 
    - docker push $BUILDER_IMAGE_TAG


#staging:
#  stage: staging
#  variables:
#    HEROKU_API_KEY: $HEROKU_STAGING_API_KEY
#  script:
#    - echo "deb http://toolbelt.heroku.com/ubuntu ./" > /etc/apt/sources.list.d/heroku.list
#    - wget -O- https://toolbelt.heroku.com/apt/release.key | apt-key add -
#    - apt-get update
#    - apt-get install -y -qq nodejs build-essential heroku-toolbelt
#    - gem install dpl
#    - dpl --provider=heroku --app=staging-masonicmanagement --api-key=$HEROKU_STAGING_API_KEY
#    - heroku run rake db:migrate db:seed --exit-code --app staging-masonicmanagement
#  only:
#    - develop
