version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: masonicmanagement
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    image: registry.gitlab.com/trixsystems/trxmasonic/masonicmanagement:develop
    depends_on:     
      - db
    ports: 
      - 3000:3000
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env

#  sidekiq:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - app      
#      - database
#      - redis
#    volumes:
#      - .:/app
#      - gem_cache:/usr/local/bundle/gems
#      - node_modules:/app/node_modules
#    env_file: .env
#    environment:
#      RAILS_ENV: development
#    entrypoint: ./entrypoints/sidekiq-entrypoint.sh

volumes:
  gem_cache:
  db_data:
  node_modules:
