version: '3.4'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: masonicmanagement
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

#  redis:
#    image: redis:5.0.9
#    ports:
#      - 6379:6379

  app: 
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:     
      - db
      # - redis
    ports: 
      - 3000:3000
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development

#  sidekiq:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - app      
#      - database
#      - redis
#    volumes:
#      - .:/app
#      - gem_cache:/usr/local/bundle/gems
#      - node_modules:/app/node_modules
#    env_file: .env
#    environment:
#      RAILS_ENV: development
#    entrypoint: ./entrypoints/sidekiq-entrypoint.sh

volumes:
  gem_cache:
  db_data:
  node_modules:
