version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: masonicmanagement
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    image: registry.gitlab.com/trixsystems/trxmasonic/masonicmanagement:develop
    depends_on:     
      - db
    ports: 
      - 3000:3000
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    # env_file: .env
    environment:
      SECRET_KEY_BASE: ./config/credentials.yml.enc
      # vjXUojVrhp1PUW0bibiVaMjo47kPfR19Ysh+h3uQiFlA7TaKRz0JRbtpOSIvlEjgDYKzwWdeaFOwwoytqD+H+Uz2jl0EHZETXYShLC4EGj/ulxxzx1PL7gQXoYmh7ehv0tYOq+PBqk02YBf/n8rdYkjUJ3pR2aZnKQSkl8XLZ9F7AKt5aaAUm1lYZGY46uHf1CPadcCCC16MZG00ASb2JG0wlP633x/XOTL2EqoU0piXlgBg3B/0YgRIAHARvffb7Nd03DvPlc61cUY554VbEzEBFK2+ws4zdungxBHmIZaxaPBkLjUIz2dwz8NHzq8hKQnJwm1R+6dSqgeOayqna4bWcILO1RCLx3xpM3ZlD/vzD3k84fCf2QbJUlbh8WOVK7SNy+EqAc2rcSAZ3pz0S80MvkC7ZcM6iper--rCZEyBRmVGeahwWc--U+7XJgNMEBxRJU8UnUu1cA==
      # RAILS_ENV: development

#  sidekiq:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - app      
#      - database
#      - redis
#    volumes:
#      - .:/app
#      - gem_cache:/usr/local/bundle/gems
#      - node_modules:/app/node_modules
#    env_file: .env
#    environment:
#      RAILS_ENV: development
#    entrypoint: ./entrypoints/sidekiq-entrypoint.sh

volumes:
  gem_cache:
  db_data:
  node_modules:
