version: '3.7'

services:
  web:
    image: nginx
    ports:
      - 80:80

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: masonicmanagement
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    
  app:
    build: .
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
    environment:
      - RAILS_ENV=${RAILS_ENV}
    depends_on:
      - db