source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.0'

gem 'rails', '~> 6.1.4', '>= 6.1.4.4'
gem 'pg', '~> 1.2', '>= 1.2.3'
gem 'puma', '~> 5.5', '>= 5.5.2'
gem 'sass-rails', '~> 6.0'
gem 'webpacker', '~> 5.4', '>= 5.4.3'
gem 'turbolinks', '~> 5.2', '>= 5.2.1'
gem 'jbuilder', '~> 2.11', '>= 2.11.5'
gem 'bootsnap', '~> 1.10', '>= 1.10.3', require: false
gem 'devise', '~> 4.8', '>= 4.8.1'
gem 'devise-i18n', '~> 1.10', '>= 1.10.1'
gem 'rails-i18n', '~> 7.0', '>= 7.0.1'
gem 'simple_form', '~> 5.1'
gem 'kaminari', '~> 1.2', '>= 1.2.2'
gem 'groupdate', '~> 6.0', '>= 6.0.1'
gem 'net-smtp', '~> 0.3.1'
gem 'net-pop', '~> 0.1.1'
gem 'net-imap', '~> 0.2.3'
gem 'nokogiri', '~> 1.13', '>= 1.13.1'
gem 'geokit', '~> 1.13', '>= 1.13.1'
gem 'bootstrap', '~> 5.1.3'
gem 'sidekiq', '~> 6.4', '>= 6.4.1'
gem 'uglifier', '~> 4.2'
gem "font-awesome-rails"
gem 'carrierwave', '~>2.0'
gem 'image_processing', '>=1.2'
gem 'mini_magick'


group :development, :test do
  gem 'byebug', '~> 11.1', '>= 11.1.3', platforms: [:mri, :mingw, :x64_mingw]
  gem "factory_bot_rails"
  gem "rspec-rails"
  gem "rubycritic"
end

group :development do
  gem 'web-console'
  gem 'rack-mini-profiler'
  gem 'listen'
  gem 'spring'
  gem 'spring-watcher-listen'
  gem 'better_errors', '~> 2.9', '>= 2.9.1'
  gem 'binding_of_caller', '~> 1.0'
  gem 'faker', '~> 2.19'
  gem 'brakeman', '~> 5.2'
  gem 'pry', '~> 0.14.1'
  gem 'annotate', '~> 3.1', '>= 3.1.1'
end

group :test do
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'webdrivers'
  gem "database_cleaner"
  gem "shoulda-matchers"
  gem "simplecov"
end
